version: '3'

services:
  db:
    image: 'postgres:14.4-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=recipedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - "./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 5s
      retries: 10

  web:
    image: 'recipe:latest'
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/recipedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - 8080:8080

volumes:
  postgres_data: